version: '3.7'
services:
  hhapp-back-prod:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: production-stage
    ports:
      - '3000:3000'
    command: sh -c '/wait-for -t 60 hhapp-back-prod-database:3306 -- pm2-runtime start ecosystem.prod.config.js'
    depends_on:
      - hhapp-back-prod-database
    environment:
      DB_HOST: 'hhapp-back-prod-database'

  # Database
  hhapp-back-prod-database:
    image: mariadb
    restart: always
    volumes:
      - ./.docker/production/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'hhapp'
      MYSQL_USER: 'hhapp'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306'

