version: '3.7'
services:
  # Run compiled app in watch mode
  hhapp-back-dev:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    ports:
    - '3000:3000'
    - '9229:9229' # Node debug
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules' # Used to keep all modules inside container
    command: sh -c '/wait-for -t 60 hhapp-back-dev-database:3306 -- pm2-runtime start ./.docker/dev/ecosystem.config.js --only hhapp-back-dev --no-auto-exit'
    depends_on:
      - hhapp-back-dev-database
    environment:
      DB_HOST: 'hhapp-back-dev-database'

        # Run compiled app in watch mode
  hhapp-back-dev-watcher:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules' # Used to keep all modules inside container
    command: sh -c 'pm2-runtime start ./.docker/dev/ecosystem.config.js --only hhapp-back-dev-watcher'
    environment:
      DB_HOST: 'hhapp-back-dev-database'

  # Database
  hhapp-back-dev-database:
    image: mariadb
    restart: 'no'
    volumes:
      - .docker/dev/mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'hhapp'
      MYSQL_USER: 'hhapp'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306'

